# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMS_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 100, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_freq_value = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(48)
        self.lbl_freq_value.setFont(font)
        self.lbl_freq_value.setObjectName("lbl_freq_value")
        self.gridLayout.addWidget(self.lbl_freq_value, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_volt_value = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(48)
        self.lbl_volt_value.setFont(font)
        self.lbl_volt_value.setObjectName("lbl_volt_value")
        self.gridLayout.addWidget(self.lbl_volt_value, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_curr_value = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(48)
        self.lbl_curr_value.setFont(font)
        self.lbl_curr_value.setObjectName("lbl_curr_value")
        self.gridLayout.addWidget(self.lbl_curr_value, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_pf_value = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(48)
        self.lbl_pf_value.setFont(font)
        self.lbl_pf_value.setObjectName("lbl_pf_value")
        self.gridLayout.addWidget(self.lbl_pf_value, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_voltage = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lbl_voltage.setFont(font)
        self.lbl_voltage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_voltage.setTextFormat(QtCore.Qt.RichText)
        self.lbl_voltage.setObjectName("lbl_voltage")
        self.gridLayout.addWidget(self.lbl_voltage, 0, 3, 1, 1)
        self.lbl_volt_unit = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lbl_volt_unit.setFont(font)
        self.lbl_volt_unit.setObjectName("lbl_volt_unit")
        self.gridLayout.addWidget(self.lbl_volt_unit, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_freq = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lbl_freq.setFont(font)
        self.lbl_freq.setObjectName("lbl_freq")
        self.gridLayout.addWidget(self.lbl_freq, 1, 3, 1, 1)
        self.lbl_current = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lbl_current.setFont(font)
        self.lbl_current.setObjectName("lbl_current")
        self.gridLayout.addWidget(self.lbl_current, 2, 3, 1, 1)
        self.lbl_pf = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lbl_pf.setFont(font)
        self.lbl_pf.setObjectName("lbl_pf")
        self.gridLayout.addWidget(self.lbl_pf, 3, 3, 1, 1)
        self.lbl_freq_unit = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lbl_freq_unit.setFont(font)
        self.lbl_freq_unit.setObjectName("lbl_freq_unit")
        self.gridLayout.addWidget(self.lbl_freq_unit, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_curr_unit = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lbl_curr_unit.setFont(font)
        self.lbl_curr_unit.setObjectName("lbl_curr_unit")
        self.gridLayout.addWidget(self.lbl_curr_unit, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lbl_pf_unit = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lbl_pf_unit.setFont(font)
        self.lbl_pf_unit.setObjectName("lbl_pf_unit")
        self.gridLayout.addWidget(self.lbl_pf_unit, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecording = QtWidgets.QMenu(self.menubar)
        self.menuRecording.setObjectName("menuRecording")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSelectPort = QtWidgets.QAction(MainWindow)
        self.actionSelectPort.setObjectName("actionSelectPort")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuRecording.addAction(self.actionStart)
        self.menuRecording.addAction(self.actionStop)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRecording.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionStart.triggered.connect(MainWindow.startRecording)
        self.actionStop.triggered.connect(MainWindow.stopRecording)
        self.actionAbout.triggered.connect(MainWindow.onAbout)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "منظومة مراقبة الجهد"))
        self.lbl_freq_value.setText(_translate("MainWindow", "00.0"))
        self.lbl_volt_value.setText(_translate("MainWindow", "000"))
        self.lbl_curr_value.setText(_translate("MainWindow", "000"))
        self.lbl_pf_value.setText(_translate("MainWindow", "0.00"))
        self.lbl_voltage.setText(_translate("MainWindow", "الجهد"))
        self.lbl_volt_unit.setText(_translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">ac</span></p></body></html>"))
        self.lbl_freq.setText(_translate("MainWindow", "التردد"))
        self.lbl_current.setText(_translate("MainWindow", "التيار"))
        self.lbl_pf.setText(_translate("MainWindow", "عامل القدرة"))
        self.lbl_freq_unit.setText(_translate("MainWindow", "<html><head/><body><p>H<span style=\" vertical-align:sub;\">z</span></p></body></html>"))
        self.lbl_curr_unit.setText(_translate("MainWindow", "<html><head/><body><p>A<span style=\" vertical-align:sub;\">ac</span></p></body></html>"))
        self.lbl_pf_unit.setText(_translate("MainWindow", "%"))
        self.menuFile.setTitle(_translate("MainWindow", "ملف"))
        self.menuRecording.setTitle(_translate("MainWindow", "تسجيل"))
        self.menuHelp.setTitle(_translate("MainWindow", "مساعدة"))
        self.actionStart.setText(_translate("MainWindow", "ابدأ التسجيل"))
        self.actionStop.setText(_translate("MainWindow", "أوقف التسجيل"))
        self.actionAbout.setText(_translate("MainWindow", "حول"))
        self.actionExit.setText(_translate("MainWindow", "خروج"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+F4"))
        self.actionSelectPort.setText(_translate("MainWindow", "اختيار المنفذ"))

